spring:
  profiles:
    active: ao
  application:
    name: rwa-engine
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    time-zone: GMT+8

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"

  server:
    port: 18090
    address: 127.0.0.1

server:
  port: 8090
  servlet:
    context-path: /rwa-engine

mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    call-setters-on-nulls: true
  type-handlers-package: com.amarsoft.rwa.engine.config.handler

logging:
  level:
    root: info
    com.amarsoft: debug
    org.springframework.jdbc.core.JdbcTemplate: debug
  file:
    path: logs
